// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropostaService.Infrastructure.Persistence.Context;

#nullable disable

namespace PropostaService.Infrastructure.Migrations
{
    [DbContext(typeof(PropostaDbContext))]
    partial class PropostaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("propostas")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropostaService.Domain.Entities.Proposta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Propostas", "propostas");
                });

            modelBuilder.Entity("PropostaService.Domain.Entities.Proposta", b =>
                {
                    b.OwnsOne("PropostaService.Domain.Entities.Cliente", "Cliente", b1 =>
                        {
                            b1.Property<Guid>("PropostaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ClienteNome");

                            b1.HasKey("PropostaId");

                            b1.ToTable("Propostas", "propostas");

                            b1.WithOwner()
                                .HasForeignKey("PropostaId");

                            b1.OwnsOne("PropostaService.Domain.ValueObjects.Cpf", "Cpf", b2 =>
                                {
                                    b2.Property<Guid>("ClientePropostaId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(11)
                                        .HasColumnType("character varying(11)")
                                        .HasColumnName("ClienteCpf");

                                    b2.HasKey("ClientePropostaId");

                                    b2.ToTable("Propostas", "propostas");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientePropostaId");
                                });

                            b1.Navigation("Cpf")
                                .IsRequired();
                        });

                    b.OwnsOne("PropostaService.Domain.Entities.Seguro", "Seguro", b1 =>
                        {
                            b1.Property<Guid>("PropostaId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("SeguroId");

                            b1.HasKey("PropostaId");

                            b1.ToTable("Propostas", "propostas");

                            b1.WithOwner()
                                .HasForeignKey("PropostaId");

                            b1.OwnsOne("PropostaService.Domain.ValueObjects.Dinheiro", "ValorCobertura", b2 =>
                                {
                                    b2.Property<Guid>("SeguroPropostaId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ValorCobertura");

                                    b2.HasKey("SeguroPropostaId");

                                    b2.ToTable("Propostas", "propostas");

                                    b2.WithOwner()
                                        .HasForeignKey("SeguroPropostaId");
                                });

                            b1.OwnsOne("PropostaService.Domain.ValueObjects.Dinheiro", "ValorPremio", b2 =>
                                {
                                    b2.Property<Guid>("SeguroPropostaId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ValorPremio");

                                    b2.HasKey("SeguroPropostaId");

                                    b2.ToTable("Propostas", "propostas");

                                    b2.WithOwner()
                                        .HasForeignKey("SeguroPropostaId");
                                });

                            b1.OwnsOne("PropostaService.Domain.ValueObjects.TipoSeguro", "Tipo", b2 =>
                                {
                                    b2.Property<Guid>("SeguroPropostaId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("TipoSeguro");

                                    b2.HasKey("SeguroPropostaId");

                                    b2.ToTable("Propostas", "propostas");

                                    b2.WithOwner()
                                        .HasForeignKey("SeguroPropostaId");
                                });

                            b1.Navigation("Tipo")
                                .IsRequired();

                            b1.Navigation("ValorCobertura")
                                .IsRequired();

                            b1.Navigation("ValorPremio")
                                .IsRequired();
                        });

                    b.Navigation("Cliente")
                        .IsRequired();

                    b.Navigation("Seguro")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
